name: Univalence Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.4.0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check formatting and linting
        run: sbt check
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        scala: [ '2.11.12', '2.12.15', '2.13.8' ]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.4.0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Run tests 2.11.X and 2.12.X
        if: ${{ !startsWith(matrix.scala, '2.13.') }}
        run: sbt ++${{ matrix.scala }}! "project core" testSpecific
      - name: Run tests 2.13.X
        if: ${{ startsWith(matrix.scala, '2.13.') }}
        run: sbt ++${{ matrix.scala }}! "project core" testSpecificWithCoverage
      - name: Publish coverage to codecov
        uses: codecov/codecov-action@v2